version: '3.8'

services:
  blazor-app:
    image: akeshman1908/frontend-blazor-app:latest  # Gebruik je gepushte image op Docker Hub
    ports:
      - "5000:80"  # Expose de app op poort 5000 op de host en map naar poort 80 in de container
    networks:
      - blazor-network

networks:
  blazor-network:
    driver: bridge
